<a href="https://colab.research.google.com/github/AYOUBSEDDOUKI/AYOUBSEDDOUKI/blob/main/RLM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.datasets import make_regression
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
data = pd.read_csv("/content/Marketing_Data.csv",sep=",")

x1 =  data.iloc[:,:1].values
x2 =  data.iloc[:,1:2].values
x3 =  data.iloc[:,2:3].values

x1 = (x1-np.mean(x1))/np.std(x1)
#print(x1)
#print("*******************************************************************")
x2 = (x2-np.mean(x2))/np.std(x2)
#print(x2)
#print("*******************************************************************")
x3 = (x3-np.mean(x3))/np.std(x3)
#print(x3)
#print("*******************************************************************")

x=x1
x = np.hstack((x,x2))
x = np.hstack((x,x3))
x = np.c_[np.ones(x.shape[0]),x]

'''
d=x[:,1:2]
d=np.hstack((d,x[:,2:3]))
d=np.hstack((d,x[:,3:4]))
d=np.hstack((d,x[:,0:1]))
'''

print(x)
print("*******************************************************************")
y =  data.iloc[:,3:4].values
y = (y-np.mean(y))/np.std(y)

[[ 1.         -0.9133766  -0.47430395  0.55255749]
 [ 1.          1.69808742  0.35207403  0.66854624]
 [ 1.         -0.41645835 -0.38024467  0.44623448]
 [ 1.         -0.60089373 -1.44848939  0.03060814]
 [ 1.          1.37738131 -0.20556315 -1.40475257]
 [ 1.         -0.61851494 -1.45520791 -1.0616192 ]
 [ 1.          1.67224297 -1.27380786 -1.0084577 ]
 [ 1.          1.39265303  1.39344467 -1.17760795]
 [ 1.         -0.86521195  1.7696818   0.78936785]
 [ 1.         -1.23643221  0.24457771  0.27708422]
 [ 1.          0.9356762   0.98361493  0.12726543]
 [ 1.          0.63611555 -0.05103718  0.10793397]
 [ 1.          0.3365549   0.69471856  0.45106734]
 [ 1.          1.70631066  0.31176291 -1.33225961]
 [ 1.          0.68780444 -0.98491149 -0.14337498]
 [ 1.         -1.44788678  0.17739251  0.6733791 ]
 [ 1.          0.31423469 -0.03760014  0.10310111]
 [ 1.         -0.6889998  -0.88413369  0.30608141]
 [ 1.          1.07547117  1.2389187  -0.52517126]
 [ 1.          0.92627822 -0.48

In [ ]:
print(x.shape)
print("************")
print(y.shape)

(171, 4)
************
(171, 1)


In [ ]:
# la formule mathematique:
Q1 = (x.T.dot(x))
Q2 = x.T.dot(y)
Q3 = np.linalg.inv(Q1)
# determiner la matrice W
W = Q3.dot(Q2)

In [ ]:
W

array([[3.30854783e-16],
       [7.33909900e-01],
       [5.34454486e-01],
       [1.68770318e-02]])

In [ ]:
resultat = x.dot(W)
print(resultat)

In [ ]:
from sklearn.metrics import r2_score as R2
r2 = R2(y,resultat)
print("le R2 :",r2)
n=len(x[:,0])
p=len(x[0,:])
R2_ajusté = 1 - ((1-r2)*(n-1))/(n-1-p)
print("le R2 ajusté:",R2_ajusté)

le R2 : 0.9004752358539351
le R2 ajusté: 0.8980770487660781


In [ ]:
np.random.seed(0) # pour produire toujours le meme vecteur theta aléatoire
theta = np.random.randn(4, 1)
theta

array([[1.76405235],
       [0.40015721],
       [0.97873798],
       [2.2408932 ]])

In [ ]:
# defintion de model
def model(X,w):
    return X.dot(w)


In [ ]:
def cost_function(X, y, theta):
    return -2*np.sum((model(X, theta) - y)**2)

In [ ]:
cost_function(x, y, theta)

-3028.8219872078253

In [ ]:
def grad(X, y, theta):
    return X.T.dot(model(X, theta) - y)


In [ ]:
def gradient_descent(X, y, theta, learning_rate, n_iterations):
    
    cost_history = np.zeros(n_iterations) # création d'un tableau de stockage pour enregistrer l'évolution du Cout du modele
    
    for i in range(0, n_iterations):
        theta = theta - learning_rate * grad(X, y, theta) # mise a jour du parametre theta (formule du gradient descent)
        cost_history[i] = cost_function(X, y, theta) # on enregistre la valeur du Cout au tour i dans cost_history[i]
        
    return theta, cost_history

In [ ]:
n_iterations = 1000
learning_rate = 0.01

theta_final, cost_history = gradient_descent(x, y, theta, learning_rate, n_iterations)

In [ ]:
theta_final

array([[4.68180074e+100],
       [1.32213542e+116],
       [2.31229351e+116],
       [2.36212339e+116]])

In [ ]:
predictions = model(x, theta_final)
#print(predictions)

In [ ]:
from sklearn.metrics import r2_score as R2
r2 = R2(y,predictions)
print("le R2 :",r2)
n=len(x[:,0])
p=len(x[0,:])
R2_ajusté = 1 - ((1-r2)*(n-1))/(n-1-p)
print("le R2 ajusté:",R2_ajusté)


le R2 : -1.7100642005131436e+233
le R2 ajusté: -1.7512705667905687e+233
